// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decks.sql

package sqlitedb

import (
	"context"
	"time"
)

const createDeck = `-- name: CreateDeck :exec
INSERT INTO decks (id, name, format, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateDeckParams struct {
	ID        string    `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Format    string    `db:"format" json:"format"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) error {
	_, err := q.db.ExecContext(ctx, createDeck,
		arg.ID,
		arg.Name,
		arg.Format,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDeck = `-- name: DeleteDeck :exec
DELETE FROM decks WHERE id = ?
`

func (q *Queries) DeleteDeck(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDeck, id)
	return err
}

const getDeck = `-- name: GetDeck :one
SELECT id, name, format, created_at, updated_at
FROM decks
WHERE id = ?
`

func (q *Queries) GetDeck(ctx context.Context, id string) (Deck, error) {
	row := q.db.QueryRowContext(ctx, getDeck, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDecks = `-- name: ListDecks :many
SELECT id, name, format, created_at, updated_at
FROM decks
ORDER BY updated_at DESC
`

func (q *Queries) ListDecks(ctx context.Context) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, listDecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeck = `-- name: UpdateDeck :exec
UPDATE decks
SET name = ?, format = ?, updated_at = ?
WHERE id = ?
`

type UpdateDeckParams struct {
	Name      string    `db:"name" json:"name"`
	Format    string    `db:"format" json:"format"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
	ID        string    `db:"id" json:"id"`
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) error {
	_, err := q.db.ExecContext(ctx, updateDeck,
		arg.Name,
		arg.Format,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
