// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package sqlitedb

import (
	"context"
)

const createEntry = `-- name: CreateEntry :exec
INSERT INTO deck_entries (id, deck_id, card_id, name, set_code, number, count, section, position)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEntryParams struct {
	ID       string `db:"id" json:"id"`
	DeckID   string `db:"deck_id" json:"deck_id"`
	CardID   string `db:"card_id" json:"card_id"`
	Name     string `db:"name" json:"name"`
	SetCode  string `db:"set_code" json:"set_code"`
	Number   string `db:"number" json:"number"`
	Count    int64  `db:"count" json:"count"`
	Section  string `db:"section" json:"section"`
	Position int64  `db:"position" json:"position"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) error {
	_, err := q.db.ExecContext(ctx, createEntry,
		arg.ID,
		arg.DeckID,
		arg.CardID,
		arg.Name,
		arg.SetCode,
		arg.Number,
		arg.Count,
		arg.Section,
		arg.Position,
	)
	return err
}

const deleteEntriesByDeck = `-- name: DeleteEntriesByDeck :exec
DELETE FROM deck_entries WHERE deck_id = ?
`

func (q *Queries) DeleteEntriesByDeck(ctx context.Context, deckID string) error {
	_, err := q.db.ExecContext(ctx, deleteEntriesByDeck, deckID)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM deck_entries WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, deck_id, card_id, name, set_code, number, count, section, position
FROM deck_entries
WHERE id = ?
`

func (q *Queries) GetEntry(ctx context.Context, id string) (DeckEntry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i DeckEntry
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.CardID,
		&i.Name,
		&i.SetCode,
		&i.Number,
		&i.Count,
		&i.Section,
		&i.Position,
	)
	return i, err
}

const listEntriesByDeck = `-- name: ListEntriesByDeck :many
SELECT id, deck_id, card_id, name, set_code, number, count, section, position
FROM deck_entries
WHERE deck_id = ?
ORDER BY section, position
`

func (q *Queries) ListEntriesByDeck(ctx context.Context, deckID string) ([]DeckEntry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeckEntry
	for rows.Next() {
		var i DeckEntry
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.CardID,
			&i.Name,
			&i.SetCode,
			&i.Number,
			&i.Count,
			&i.Section,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntryCount = `-- name: UpdateEntryCount :exec
UPDATE deck_entries
SET count = ?
WHERE id = ?
`

type UpdateEntryCountParams struct {
	Count int64  `db:"count" json:"count"`
	ID    string `db:"id" json:"id"`
}

func (q *Queries) UpdateEntryCount(ctx context.Context, arg UpdateEntryCountParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryCount, arg.Count, arg.ID)
	return err
}

const upsertEntry = `-- name: UpsertEntry :exec
INSERT INTO deck_entries (id, deck_id, card_id, name, set_code, number, count, section, position)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET count = excluded.count, position = excluded.position
`

type UpsertEntryParams struct {
	ID       string `db:"id" json:"id"`
	DeckID   string `db:"deck_id" json:"deck_id"`
	CardID   string `db:"card_id" json:"card_id"`
	Name     string `db:"name" json:"name"`
	SetCode  string `db:"set_code" json:"set_code"`
	Number   string `db:"number" json:"number"`
	Count    int64  `db:"count" json:"count"`
	Section  string `db:"section" json:"section"`
	Position int64  `db:"position" json:"position"`
}

func (q *Queries) UpsertEntry(ctx context.Context, arg UpsertEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntry,
		arg.ID,
		arg.DeckID,
		arg.CardID,
		arg.Name,
		arg.SetCode,
		arg.Number,
		arg.Count,
		arg.Section,
		arg.Position,
	)
	return err
}
