// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"time"
)

type Deck struct {
	ID        string    `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Format    string    `db:"format" json:"format"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type DeckEntry struct {
	ID       string `db:"id" json:"id"`
	DeckID   string `db:"deck_id" json:"deck_id"`
	CardID   string `db:"card_id" json:"card_id"`
	Name     string `db:"name" json:"name"`
	SetCode  string `db:"set_code" json:"set_code"`
	Number   string `db:"number" json:"number"`
	Count    int64  `db:"count" json:"count"`
	Section  string `db:"section" json:"section"`
	Position int64  `db:"position" json:"position"`
}
